#pragma config(Sensor, dgtl1,  reverseOn,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  reverseOff,     sensorDigitalOut)
#pragma config(Sensor, dgtl6,  highCharge,     sensorDigitalOut)
#pragma config(Sensor, dgtl7,  midCharge,      sensorDigitalOut)
#pragma config(Sensor, dgtl8,  lowCharge,      sensorDigitalOut)
#pragma config(Motor,  port2,           fRbR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fLbL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           forkLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           forkRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           clawLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           clawRight,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool pressed = false;
	const int speed = 0.5;
	int motorSwitch = 1;

	while(true)
	{
		int batteryCharge = nImmediateBatteryLevel;
		if(vexRT[Btn7L])
		{
			if(!pressed)
			{
				motorSwitch *= -1;
			}
			pressed = true;
			} else {
			pressed = false;
		}
		motor(fRbR) = (vexRT[Ch3] - (vexRT[Ch4] * (speed))) * motorSwitch;
		motor(fLbL) = (vexRT[Ch3] + (vexRT[Ch4] * (speed))) * motorSwitch;

		motor(armRight) = vexRT[Ch2];
		motor(armLeft) = vexRT[Ch2];

		motor(clawLeft) = 126 * vexRT[Btn5U]- (126 * vexRT[Btn5D]);
		motor(clawRight) = 126 * vexRT[Btn5U] - (126 * vexRT[Btn5D]);
							 
		motor(forkRight) =  126 * vexRT[Btn6U]- (126 * vexRT[Btn6D]);
		motor(forkRight) =  126 * vexRT[Btn6U]- (126 * vexRT[Btn6D]);
		
		if(motorSwitch == -1) {
			SensorValue[reverseOn] = true;
			SensorValue[reverseOff] = false;
		}
		else if(motorSwitch == 1) {
			SensorValue[reverseOn] = false;
			SensorValue[reverseOff] = true;
		}
	}
}
