#pragma config(Sensor, dgtl1,  reverseOn,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  reverseOff,     sensorDigitalOut)
#pragma config(Motor,  port1,           clawMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           fRbR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           forkLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           forkRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           fLbL,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool pressed = false;
	int motorSwitch = 1;

	while(true)
	{
		int batteryCharge = nImmediateBatteryLevel;
		if(vexRT[Btn7L])
		{
			if(!pressed)
			{
				motorSwitch *= -1;
			}
			pressed = true;
			} else {
			pressed = false;
		}
		motor(fRbR) = vexRT[Ch3] - (vexRT[Ch4] * motorSwitch);
		motor(fLbL) = vexRT[Ch3] + (vexRT[Ch4] * motorSwitch);

		motor(forkRight) = vexRT[Ch2];
		motor(forkLeft) = vexRT[Ch2];

		motor(armRight) = (126 * vexRT[Btn8U]) - (126 * vexRT[Btn8D]);
		motor(armLeft) = (126 * vexRT[Btn8U]) - (126 * vexRT[Btn8D]);

		motor(clawMotor) = (126 * vexRT[Btn6U]) - (126 * vexRT[Btn6D]);

		if(motorSwitch == -1) {
			SensorValue[reverseOn] = true;
			SensorValue[reverseOff] = false;
			}	else if(motorSwitch == 1) {
			SensorValue[reverseOn] = false;
			SensorValue[reverseOff] = true;
		}
	}
}
