#pragma config(Motor,  port2,           fRbR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fLbL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armRight,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool pressed = false;
	const int speed = 0.5;
	int motorSwitch = 1;

	while(true)
	{
		if(vexRT[Btn7L]) 
		{
			if(!pressed)
			{
				motorSwitch *= -1;
			}
			pressed = true;
			} else {
			pressed = false;
		}
		motor(fRbR) = (vexRT[Ch3] - (vexRT[Ch4] * (speed))) * motorSwitch;
		motor(fLbL) = (vexRT[Ch3] + (vexRT[Ch4] * (speed))) * motorSwitch;

		motor(armRight) = vexRT[Ch2];
		motor(armLeft) = vexRT[Ch2];
	}

}
