#pragma config(Motor,  port2,           fRbR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fLbL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           linearLeft,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           linearRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armLeft,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armRight,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor(fRbR) = vexRT[Ch3] - (vexRT[Ch4] * 0.5);
		motor(fLbL) = vexRT[Ch3] + (vexRT[Ch4] * 0.5);
		//motor(linearLeft) = (vexRT[Btn5U])*126;
		//motor(linearRight) = (vexRT[Btn5D])*126;
		//motor(armLeft) = vexRT[Ch2];
		//motor(armRight) = vexRT[Ch2];
	}
}
