#pragma config(Motor,  port2,           fRbR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fLbL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           clawLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           clawRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           linearLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           linearRight,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
	bool pressed = false;
	const int speed = 0.5;
	int motorSwitch = 1;
	while(true)
	{
		if(vexRT[Btn7L]) {
			if(!pressed)
			{
				motorSwitch *= -1;
			}
			pressed = true;
			} else {
			pressed = false;
		}
	}
	motor(fRbR) = (vexRT[Ch3] - (vexRT[Ch4] * (speed))) * motorSwitch;
	motor(fLbL) = (vexRT[Ch3] + (vexRT[Ch4] * (speed))) * motorSwitch;

	motor(armRight) = vexRT[Ch2];
	motor(armLeft) = vexRT[Ch2];

	motor(linearRight) = vexRT[Btn8U];
	motor(linearLeft) = vexRT[Btn8D];

	motor(clawRight) = vexRT[Btn6U];
	motor(clawLeft) = vexRT[Btn6D];
}
