#pragma config(Motor,  port2,           fRbR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fLbL,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		motor(fRbR) = vexRT[Ch3] + vexRT[Ch2];
		motor(fLbL) = vexRT[Ch3] - vexRT[Ch2];
	}
}
