#pragma config(Sensor, dgtl1,  reverseOn,      sensorDigitalOut)
#pragma config(Sensor, dgtl2,  reverseOff,     sensorDigitalOut)
#pragma config(Sensor, dgtl3,  forkSwitch,     sensorTouch)
#pragma config(Sensor, dgtl4,  armSwitch,      sensorTouch)#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  coneArm,        sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  mogo,           sensorQuadEncoder)
#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           topRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           fRbR,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           fLbL,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           chainArm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           bottomRight,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottomLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           topLeft,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
	SensorValue[coneArm]  = 0;
	SensorValue[mogo] = 0;
}

//7 inch cone; 4 inches half height

//void autoStack() {
//	while(autoSwitch == 1) {

//		for(int i=0; i < 5; i++) {
//			motor(armLeft) = 126;
//			motor(armRight) = 126;
//			wait1Msec(200 * i);
//			motor(armLeft) = -126;
//			motor(armRight) = -126;
//			wait1Msec(200 * i);
//		}
//	}
//}

task autonomous()
{
	motor(chainArm) = 57;
	wait1Msec(500);
	motor(chainArm) = 0;
	motor(topRight) = -67;
	motor(topLeft) = -67;
	motor(bottomLeft) = -67;
	motor(bottomRight) = -67;
	motor(lift) = -50;
	wait1Msec(1000);
	motor(chainArm) = 0;
	motor(topRight) = 0;
	motor(topLeft) = 0;
	motor(bottomLeft) = 0;
	motor(bottomRight) = 0;
	motor(fLbL) = 127;
	motor(fRbR) = 127;
	wait1Msec(2100);
	motor(lift) = 87;
	motor(fLbL) = 0;
	motor(fRbR) = 0;
	wait1Msec(1500);
	motor(topRight) = 67;
	motor(topLeft) = 67;
	motor(bottomLeft) = 67;
	motor(bottomRight) = 67;
	wait1Msec(300);
	motor(topRight) = 0;
	motor(topLeft) = 0;
	motor(bottomLeft) = 0;
	motor(bottomRight) = 0;
	motor(fLbL) = -127;
	motor(fRbR) = -127;
	motor(lift) = 0;
	motor(intake) = 100;
	wait1Msec(2200);
	motor(fLbL) = -67;
	motor(fRbR) = 67;
	motor(intake) = 0;
	wait1Msec(675);
	motor(fLbL) = 127;
	motor(fRbR) = 127;
	wait1Msec(500);
	motor(fLbL) = -67;
	motor(fRbR) = 67;
	wait1Msec(1100);
	motor(fLbL) = 127;
	motor(fRbR) = 127;
	wait1Msec(1000);
	motor(lift) = -127;
	wait1Msec(1750);
	motor(fLbL) = -127;
	motor(fRbR) = -127;
	motor(lift) = 67;
	wait1Msec(500);
}

task usercontrol() {
	int stacked = 0;
	bool pressed = false;
	int motorSwitch = 1;
	int armState = 1;

	//int ticks;
	//int revs;
	//int distance;
	////distance to travel is 67

	while(true)	{
		//if(autoSwitch) {
		//	autoStack();
		//}
		motor(fRbR) = (vexRT[Ch3] * motorSwitch) - vexRT[Ch4];
		motor(fLbL) = (vexRT[Ch3] * motorSwitch) + vexRT[Ch4];

		motor(lift) = (126 * vexRT[Btn6D]) - (126 * vexRT[Btn6U]);

		motor(chainArm) = ((126 * vexRT[Btn7U]) * SensorValue[coneArm] > -150 ? 1 : 0) - ((126 * vexRT[Btn7D]) * SensorValue[coneArm] > -55 ? 1: 0);
		motor(chainArm) = (126 * vexRT[Btn8U]) - (126 * vexRT[Btn8D]);

		motor(bottomLeft) = vexRT[Ch2];
		motor(bottomRight) = vexRT[Ch2];
		motor(topRight) = vexRT[Ch2];
		motor(topLeft) = vexRT[Ch2];

		//cone intake stopper
		if(SensorValue[coneArm] < -150) {
			motor(chainArm) = -20;
			wait1Msec(200);
		}

		//semi autostack
		if(vexRT[Btn5U] ) {
			//lower cone intake
			while(SensorValue[coneArm] > -150) {
				motor(chainArm) = 126;
				motor(intake) = -70;
			}
			motor(chainArm) = -20;
			wait1Msec(200);
			
			//lift arm
			motor(bottomLeft) = -35;
			motor(bottomRight) = -35;
			motor(topRight) = -35;
			motor(topLeft) = -35;
			wait1Msec(300);
			motor(bottomLeft) = 0;
			motor(bottomRight) = 0;
			motor(topRight) = 0;
			motor(topLeft) = 0;

			//lift cone intake
			while(SensorValue[coneArm] < -55) {
				motor(chainArm) = -126;
			}
			motor(chainArm) = 20;
			wait1Msec(200);

			//release cone
			motor(intake) = 126;
			wait1Msec(600);
			motor(intake) = 0;

			motor(bottomLeft) = -35;
			motor(bottomRight) = -35;
			motor(topRight) = -35;
			motor(topLeft) = -35;

			////lower cone intake
			//while(SensorValue[coneArm] > -150) {
			//	motor(chainArm) = 126;
			//	motor(intake) = -70;
			//}
			//motor(chainArm) = -20;
			//wait1Msec(200);

			//motor(bottomLeft) = 0;
			//motor(bottomRight) = 0;
			//motor(topRight) = 0;
			//motor(topLeft) = 0;

			motor(chainArm) = 20;
			wait1Msec(200);

			while(SensorValue[pot] > 1415) {
				motor(bottomLeft) = 35;
				motor(bottomRight) = 35;
				motor(topRight) = 35;
				motor(topLeft) = 35;
			}
			//stacked++;
			while(SensorValue[coneArm] > -130) {
				motor(chainArm) = 126;
				motor(intake) = -70;
			}
			motor(chainArm) = -30;
			wait1Msec(200);

		}

		//if(SensorValue[coneArm] < -140) {
		//	motor(chainArm) = -20;
		//	wait1Msec(200);
		//	motor(chainArm) = 0;

		//}

		motor(intake) = (126 * vexRT[Btn8L]) - (126 * vexRT[Btn8R]) - 17;
		if(vexRT[Btn7R]) {
			if(armState == 1) {
				while(SensorValue[coneArm] > -150) {
					motor(chainArm) = 126;
					motor(intake) = -70;
				}
				motor(chainArm) = -20;
				wait1Msec(200);
				//while(SensorValue[pot] > value) {
				//	motor(bottomLeft) = (insertValueHere);
				//	motor(bottomRight) = (insertValueHere);
				//	motor(topRight) = (insertValueHere);
				//	motor(topLeft) = (insertValueHere);
				//}
			}
			if(armState == -1) {
				while(SensorValue[coneArm] < -50) {
					motor(chainArm) = -126;
				}
				motor(chainArm) = 20;
				wait1Msec(200);
				//while(SensorValue[pot] > value) {
				//	motor(bottomLeft) = (insertValueHere);
				//	motor(bottomRight) = (insertValueHere);
				//	motor(topRight) = (insertValueHere);
				//	motor(topLeft) = (insertValueHere);
				//}
			}
			if(!pressed) {
				armState *= -1;
			}
			pressed = true;
			} else {
			pressed = false;
		}
	}
}
#pragma config(Motor,  port2,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           fRbR,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           fLbL,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRight,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armTwoLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armTwoRight,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{
	//lower fork
	//motor[forkLeft] = 120;
	//motor[forkRight] = 120;
	//wait1Msec(1500);
	////stop fork; move forward
	//motor[forkLeft]= 0;
	//motor[forkRight] = 0;
	//motor[fLbL] = 127;
	//motor[fRbR] = 127;
	//wait1Msec(1350);
	////stop moving
	//motor[fRbR] = 0;
	//motor[fLbL] = 0;
	////raise fork
	//motor[forkLeft] = -120;
	//motor[forkRight] = -120;
	//wait1Msec(1600);
	//motor[forkLeft] = 0;
	//motor[forkRight] = 0;
	////back out (reverse)
	//motor[fRbR] = -120;
	//motor[fLbL] = -120;
	//wait1Msec(900);
	////turn robot
	//motor[fRbR] = 120;
	//motor[fLbL] = -80;
	//wait1Msec(650);
	////move foward
	//motor[fRbR] = 120;
	//motor[fLbL] = 120;
	//wait1Msec(500);
	////stop motors; lower forks
	//motor[fRbR] = 120;
	//motor[fLbL] = -80;
	//wait1Msec(450);
	//motor[fRbR] = 120;
	//motor[fLbL] = 80;
	//wait1Msec(800);
	//motor[fLbL] = 0;
	//motor[fRbR] = 0;
	//motor[pusherMotor] = 80;
	//motor[forkLeft] = 120;
	//motor[forkRight] = 120;
	//wait1Msec(1500);
	//motor[fLbL] = -80;
	//motor[fRbR] = -120;
	//motor[forkLeft] = -50;
	//motor[forkRight] = -50;
	//wait1Msec(800);
	////stop motors
	//motor[fLbL] = 0;
	//motor[fRbR] = 0;



	//set up for 10
	/*
	motor[forkLeft] = 80;
	motor[forkRight] = 80;
	wait1Msec(2000);
	motor[forkLeft] = 0;
	motor[forkRight] = 0;
	//bring cone down
	wait1Msec(100);
	motor[fLbL] = -80;
	motor[fRbR] = -120;
	wait1Msec(1000);
	motor[fLbL] = 0;
	motor[fRbR] = 0;
	*/

}

task usercontrol() {
	bool pressed = false;
	int motorSwitch = 1;

	while(true)	{
		if(vexRT[Btn7L]) {
			if(!pressed) {
				motorSwitch *= -1;
			}
			pressed = true;
			} else {
			pressed = false;
		}
		motor(fRbR) = (vexRT[Ch3] * motorSwitch) - vexRT[Ch4];
		motor(fLbL) = (vexRT[Ch3] * motorSwitch) + vexRT[Ch4];

		motor(lift) = (126 * vexRT[Btn5U]) - (126 * vexRT[Btn5D]);

		motor(armLeft) = vexRT[Ch2];
		motor(armRight) = vexRT[Ch2];

		motor(armTwoLeft) = vexRT[Ch2];
		motor(armTwoRight) = vexRT[Ch2];

		motor(intake) = 10;
		motor(intake) = (120 * vexRT[Btn8L]) - (120 * vexRT[Btn8R]);

	}
}
